// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quantities/quantities.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "quantities/quantities.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace principia {
namespace serialization {

namespace {

const ::google::protobuf::Descriptor* Quantity_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Quantity_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_quantities_2fquantities_2eproto() {
  protobuf_AddDesc_quantities_2fquantities_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "quantities/quantities.proto");
  GOOGLE_CHECK(file != NULL);
  Quantity_descriptor_ = file->message_type(0);
  static const int Quantity_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quantity, dimensions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quantity, magnitude_),
  };
  Quantity_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Quantity_descriptor_,
      Quantity::default_instance_,
      Quantity_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quantity, _has_bits_[0]),
      -1,
      -1,
      sizeof(Quantity),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Quantity, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_quantities_2fquantities_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Quantity_descriptor_, &Quantity::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_quantities_2fquantities_2eproto() {
  delete Quantity::default_instance_;
  delete Quantity_reflection_;
}

void protobuf_AddDesc_quantities_2fquantities_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033quantities/quantities.proto\022\027principia"
    ".serialization\"1\n\010Quantity\022\022\n\ndimensions"
    "\030\001 \002(\004\022\021\n\tmagnitude\030\002 \002(\001", 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "quantities/quantities.proto", &protobuf_RegisterTypes);
  Quantity::default_instance_ = new Quantity();
  Quantity::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_quantities_2fquantities_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_quantities_2fquantities_2eproto {
  StaticDescriptorInitializer_quantities_2fquantities_2eproto() {
    protobuf_AddDesc_quantities_2fquantities_2eproto();
  }
} static_descriptor_initializer_quantities_2fquantities_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Quantity::kDimensionsFieldNumber;
const int Quantity::kMagnitudeFieldNumber;
#endif  // !_MSC_VER

Quantity::Quantity()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:principia.serialization.Quantity)
}

void Quantity::InitAsDefaultInstance() {
}

Quantity::Quantity(const Quantity& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:principia.serialization.Quantity)
}

void Quantity::SharedCtor() {
  _cached_size_ = 0;
  dimensions_ = GOOGLE_ULONGLONG(0);
  magnitude_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Quantity::~Quantity() {
  // @@protoc_insertion_point(destructor:principia.serialization.Quantity)
  SharedDtor();
}

void Quantity::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Quantity::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Quantity::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Quantity_descriptor_;
}

const Quantity& Quantity::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_quantities_2fquantities_2eproto();
  return *default_instance_;
}

Quantity* Quantity::default_instance_ = NULL;

Quantity* Quantity::New(::google::protobuf::Arena* arena) const {
  Quantity* n = new Quantity;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Quantity::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Quantity*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(dimensions_, magnitude_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Quantity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:principia.serialization.Quantity)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 dimensions = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &dimensions_)));
          set_has_dimensions();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_magnitude;
        break;
      }

      // required double magnitude = 2;
      case 2: {
        if (tag == 17) {
         parse_magnitude:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &magnitude_)));
          set_has_magnitude();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:principia.serialization.Quantity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:principia.serialization.Quantity)
  return false;
#undef DO_
}

void Quantity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:principia.serialization.Quantity)
  // required uint64 dimensions = 1;
  if (has_dimensions()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->dimensions(), output);
  }

  // required double magnitude = 2;
  if (has_magnitude()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->magnitude(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:principia.serialization.Quantity)
}

::google::protobuf::uint8* Quantity::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:principia.serialization.Quantity)
  // required uint64 dimensions = 1;
  if (has_dimensions()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->dimensions(), target);
  }

  // required double magnitude = 2;
  if (has_magnitude()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->magnitude(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:principia.serialization.Quantity)
  return target;
}

int Quantity::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_dimensions()) {
    // required uint64 dimensions = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dimensions());
  }

  if (has_magnitude()) {
    // required double magnitude = 2;
    total_size += 1 + 8;
  }

  return total_size;
}
int Quantity::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint64 dimensions = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->dimensions());

    // required double magnitude = 2;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Quantity::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Quantity* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Quantity*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Quantity::MergeFrom(const Quantity& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dimensions()) {
      set_dimensions(from.dimensions());
    }
    if (from.has_magnitude()) {
      set_magnitude(from.magnitude());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Quantity::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Quantity::CopyFrom(const Quantity& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Quantity::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Quantity::Swap(Quantity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Quantity::InternalSwap(Quantity* other) {
  std::swap(dimensions_, other->dimensions_);
  std::swap(magnitude_, other->magnitude_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Quantity::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Quantity_descriptor_;
  metadata.reflection = Quantity_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace serialization
}  // namespace principia

// @@protoc_insertion_point(global_scope)
