// Warning!  This file was generated by running a program (see project |tools|).
// If you change it, the changes will be lost the next time the generator is
// run.  You should change the generator instead.

extern "C"
struct NavigationFrameParameters {
  int extension;
  int centre_index;
  int primary_index;
  int secondary_index;
};

static_assert(std::is_pod<NavigationFrameParameters>::value,
              "NavigationFrameParameters is used for interfacing");

extern "C"
struct XYZ {
  double x;
  double y;
  double z;
};

static_assert(std::is_pod<XYZ>::value,
              "XYZ is used for interfacing");

extern "C"
struct AdaptiveStepParameters {
  std::int64_t max_steps;
  double length_integration_tolerance;
  double speed_integration_tolerance;
};

static_assert(std::is_pod<AdaptiveStepParameters>::value,
              "AdaptiveStepParameters is used for interfacing");

extern "C"
struct BodyParameters {
  char const* name;
  char const* gravitational_parameter;
  double reference_instant;
  char const* mean_radius;
  char const* axis_right_ascension;
  char const* axis_declination;
  char const* reference_angle;
  char const* angular_frequency;
  char const* j2;
  char const* reference_radius;
};

static_assert(std::is_pod<BodyParameters>::value,
              "BodyParameters is used for interfacing");

extern "C"
struct Burn {
  double thrust_in_kilonewtons;
  double specific_impulse_in_seconds_g0;
  NavigationFrameParameters frame;
  double initial_time;
  XYZ delta_v;
};

static_assert(std::is_pod<Burn>::value,
              "Burn is used for interfacing");

extern "C"
struct KeplerianElements {
  double eccentricity;
  double semimajor_axis;
  double mean_motion;
  double inclination_in_degrees;
  double longitude_of_ascending_node_in_degrees;
  double argument_of_periapsis_in_degrees;
  double mean_anomaly;
};

static_assert(std::is_pod<KeplerianElements>::value,
              "KeplerianElements is used for interfacing");

extern "C"
struct NavigationManoeuvre {
  Burn burn;
  double initial_mass_in_tonnes;
  double final_mass_in_tonnes;
  double mass_flow;
  double duration;
  double final_time;
  double time_of_half_delta_v;
  double time_to_half_delta_v;
  XYZ inertial_direction;
  XYZ binormal;
  XYZ normal;
  XYZ tangent;
};

static_assert(std::is_pod<NavigationManoeuvre>::value,
              "NavigationManoeuvre is used for interfacing");

extern "C"
struct QP {
  XYZ q;
  XYZ p;
};

static_assert(std::is_pod<QP>::value,
              "QP is used for interfacing");

extern "C"
struct WXYZ {
  double w;
  double x;
  double y;
  double z;
};

static_assert(std::is_pod<WXYZ>::value,
              "WXYZ is used for interfacing");

extern "C" PRINCIPIA_DLL
void CDECL principia__AdvanceTime(
    Plugin* const plugin,
    double const t,
    double const planetarium_rotation);

extern "C" PRINCIPIA_DLL
void CDECL principia__AdvanceParts(
    Plugin* const plugin,
    double const t);

extern "C" PRINCIPIA_DLL
QP CDECL principia__CelestialFromParent(
    Plugin const* const plugin,
    int const celestial_index);

extern "C" PRINCIPIA_DLL
double CDECL principia__CelestialInitialRotationInDegrees(
    Plugin const* const plugin,
    int const celestial_index);

extern "C" PRINCIPIA_DLL
WXYZ CDECL principia__CelestialRotation(
    Plugin const* const plugin,
    int const index);

extern "C" PRINCIPIA_DLL
double CDECL principia__CelestialRotationPeriod(
    Plugin const* const plugin,
    int const celestial_index);

extern "C" PRINCIPIA_DLL
WXYZ CDECL principia__CelestialSphereRotation(
    Plugin const* const plugin);

extern "C" PRINCIPIA_DLL
QP CDECL principia__CelestialWorldDegreesOfFreedom(
    Plugin const* const plugin,
    int const index,
    uint32_t const part_at_origin);

extern "C" PRINCIPIA_DLL
double CDECL principia__CurrentTime(
    Plugin const* const plugin);

extern "C" PRINCIPIA_DLL
void CDECL principia__DeletePlugin(
    Plugin const** const plugin);

extern "C" PRINCIPIA_DLL
void CDECL principia__DeleteString(
    char const** const native_string);

extern "C" PRINCIPIA_DLL
void CDECL principia__DeserializePlugin(
    char const* const serialization,
    int const serialization_size,
    PushDeserializer** const deserializer,
    Plugin const** const plugin);

extern "C" PRINCIPIA_DLL
void CDECL principia__EndInitialization(
    Plugin* const plugin);

extern "C" PRINCIPIA_DLL
bool CDECL principia__FlightPlanAppend(
    Plugin const* const plugin,
    char const* const vessel_guid,
    Burn const burn);

extern "C" PRINCIPIA_DLL
void CDECL principia__FlightPlanCreate(
    Plugin const* const plugin,
    char const* const vessel_guid,
    double const final_time,
    double const mass_in_tonnes);

extern "C" PRINCIPIA_DLL
void CDECL principia__FlightPlanDelete(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
bool CDECL principia__FlightPlanExists(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
AdaptiveStepParameters CDECL principia__FlightPlanGetAdaptiveStepParameters(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
double CDECL principia__FlightPlanGetActualFinalTime(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
double CDECL principia__FlightPlanGetDesiredFinalTime(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
double CDECL principia__FlightPlanGetInitialTime(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
NavigationManoeuvre CDECL principia__FlightPlanGetManoeuvre(
    Plugin const* const plugin,
    char const* const vessel_guid,
    int const index);

extern "C" PRINCIPIA_DLL
int CDECL principia__FlightPlanNumberOfManoeuvres(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
int CDECL principia__FlightPlanNumberOfSegments(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
void CDECL principia__FlightPlanRemoveLast(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
void CDECL principia__FlightPlanRenderedApsides(
    Plugin const* const plugin,
    char const* const vessel_guid,
    int const celestial_index,
    XYZ const sun_world_position,
    Iterator** const apoapsides,
    Iterator** const periapsides);

extern "C" PRINCIPIA_DLL
Iterator* CDECL principia__FlightPlanRenderedSegment(
    Plugin const* const plugin,
    char const* const vessel_guid,
    XYZ const sun_world_position,
    int const index);

extern "C" PRINCIPIA_DLL
bool CDECL principia__FlightPlanReplaceLast(
    Plugin const* const plugin,
    char const* const vessel_guid,
    Burn const burn);

extern "C" PRINCIPIA_DLL
bool CDECL principia__FlightPlanSetAdaptiveStepParameters(
    Plugin const* const plugin,
    char const* const vessel_guid,
    AdaptiveStepParameters const adaptive_step_parameters);

extern "C" PRINCIPIA_DLL
bool CDECL principia__FlightPlanSetDesiredFinalTime(
    Plugin const* const plugin,
    char const* const vessel_guid,
    double const final_time);

extern "C" PRINCIPIA_DLL
void CDECL principia__ForgetAllHistoriesBefore(
    Plugin* const plugin,
    double const t);

extern "C" PRINCIPIA_DLL
void CDECL principia__FreeVesselsAndPartsAndCollectPileUps(
    Plugin* const plugin);

extern "C" PRINCIPIA_DLL
int CDECL principia__GetBufferDuration();

extern "C" PRINCIPIA_DLL
int CDECL principia__GetBufferedLogging();

extern "C" PRINCIPIA_DLL
QP CDECL principia__GetPartActualDegreesOfFreedom(
    Plugin const* const plugin,
    uint32_t const part_id,
    uint32_t const part_at_origin);

extern "C" PRINCIPIA_DLL
NavigationFrame const* CDECL principia__GetPlottingFrame(
    Plugin const* const plugin);

extern "C" PRINCIPIA_DLL
int CDECL principia__GetStderrLogging();

extern "C" PRINCIPIA_DLL
int CDECL principia__GetSuppressedLogging();

extern "C" PRINCIPIA_DLL
int CDECL principia__GetVerboseLogging();

extern "C" PRINCIPIA_DLL
void CDECL principia__GetVersion(
    char const** const build_date,
    char const** const version);

extern "C" PRINCIPIA_DLL
bool CDECL principia__HasEncounteredApocalypse(
    Plugin* const plugin,
    char const** const details);

extern "C" PRINCIPIA_DLL
bool CDECL principia__HasVessel(
    Plugin* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
void CDECL principia__IncrementPartIntrinsicForce(
    Plugin* const plugin,
    uint32_t const part_id,
    XYZ const force_in_kilonewtons);

extern "C" PRINCIPIA_DLL
void CDECL principia__InsertCelestialAbsoluteCartesian(
    Plugin* const plugin,
    int const celestial_index,
    int const* const parent_index,
    BodyParameters const body_parameters,
    char const* const x,
    char const* const y,
    char const* const z,
    char const* const vx,
    char const* const vy,
    char const* const vz);

extern "C" PRINCIPIA_DLL
void CDECL principia__InsertCelestialJacobiKeplerian(
    Plugin* const plugin,
    int const celestial_index,
    int const* const parent_index,
    BodyParameters const body_parameters,
    KeplerianElements const* const keplerian_elements);

extern "C" PRINCIPIA_DLL
void CDECL principia__InsertOrKeepVessel(
    Plugin* const plugin,
    char const* const vessel_guid,
    char const* const vessel_name,
    int const parent_index,
    bool const loaded,
    bool* const inserted);

extern "C" PRINCIPIA_DLL
void CDECL principia__InsertOrKeepLoadedPart(
    Plugin* const plugin,
    uint32_t const part_id,
    char const* const name,
    double const mass_in_tonnes,
    char const* const vessel_guid,
    int const main_body_index,
    QP const main_body_world_degrees_of_freedom,
    QP const part_world_degrees_of_freedom);

extern "C" PRINCIPIA_DLL
void CDECL principia__InsertUnloadedPart(
    Plugin* const plugin,
    uint32_t const part_id,
    char const* const name,
    char const* const vessel_guid,
    QP const from_parent);

extern "C" PRINCIPIA_DLL
bool CDECL principia__IsKspStockSystem(
    Plugin* const plugin);

extern "C" PRINCIPIA_DLL
bool CDECL principia__IteratorAtEnd(
    Iterator const* const iterator);

extern "C" PRINCIPIA_DLL
void CDECL principia__IteratorDelete(
    Iterator** const iterator);

extern "C" PRINCIPIA_DLL
QP CDECL principia__IteratorGetQP(
    Iterator const* const iterator);

extern "C" PRINCIPIA_DLL
double CDECL principia__IteratorGetTime(
    Iterator const* const iterator);

extern "C" PRINCIPIA_DLL
XYZ CDECL principia__IteratorGetXYZ(
    Iterator const* const iterator);

extern "C" PRINCIPIA_DLL
void CDECL principia__IteratorIncrement(
    Iterator* const iterator);

extern "C" PRINCIPIA_DLL
int CDECL principia__IteratorSize(
    Iterator const* const iterator);

extern "C" PRINCIPIA_DLL
void CDECL principia__LogError(
    char const* const text);

extern "C" PRINCIPIA_DLL
void CDECL principia__LogFatal(
    char const* const text);

extern "C" PRINCIPIA_DLL
void CDECL principia__LogInfo(
    char const* const text);

extern "C" PRINCIPIA_DLL
void CDECL principia__LogWarning(
    char const* const text);

extern "C" PRINCIPIA_DLL
WXYZ CDECL principia__NavballOrientation(
    Plugin const* const plugin,
    XYZ const sun_world_position,
    XYZ const ship_world_position);

extern "C" PRINCIPIA_DLL
NavigationFrame* CDECL principia__NewNavigationFrame(
    Plugin const* const plugin,
    NavigationFrameParameters const parameters);

extern "C" PRINCIPIA_DLL
Plugin* CDECL principia__NewPlugin(
    char const* const game_epoch,
    char const* const solar_system_epoch,
    double const planetarium_rotation_in_degrees);

extern "C" PRINCIPIA_DLL
void CDECL principia__PrepareToReportCollisions(
    Plugin* const plugin);

extern "C" PRINCIPIA_DLL
Iterator* CDECL principia__RenderedPrediction(
    Plugin* const plugin,
    char const* const vessel_guid,
    XYZ const sun_world_position);

extern "C" PRINCIPIA_DLL
void CDECL principia__RenderedPredictionApsides(
    Plugin const* const plugin,
    char const* const vessel_guid,
    int const celestial_index,
    XYZ const sun_world_position,
    Iterator** const apoapsides,
    Iterator** const periapsides);

extern "C" PRINCIPIA_DLL
Iterator* CDECL principia__RenderedVesselTrajectory(
    Plugin const* const plugin,
    char const* const vessel_guid,
    XYZ const sun_world_position);

extern "C" PRINCIPIA_DLL
void CDECL principia__ReportCollision(
    Plugin const* const plugin,
    uint32_t const part1_id,
    uint32_t const part2_id);

extern "C" PRINCIPIA_DLL
char const* CDECL principia__SayHello();

extern "C" PRINCIPIA_DLL
char const* CDECL principia__SerializePlugin(
    Plugin const* const plugin,
    PullSerializer** const serializer);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetBufferDuration(
    int const seconds);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetBufferedLogging(
    int const max_severity);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetMainBody(
    Plugin* const plugin,
    int const index);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetPartApparentDegreesOfFreedom(
    Plugin* const plugin,
    uint32_t const part_id,
    QP const degrees_of_freedom);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetPlottingFrame(
    Plugin* const plugin,
    NavigationFrame** const navigation_frame);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetPredictionLength(
    Plugin* const plugin,
    double const t);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetStderrLogging(
    int const min_severity);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetSuppressedLogging(
    int const min_severity);

extern "C" PRINCIPIA_DLL
void CDECL principia__SetVerboseLogging(
    int const level);

extern "C" PRINCIPIA_DLL
void CDECL principia__UpdateCelestialHierarchy(
    Plugin const* const plugin,
    int const celestial_index,
    int const parent_index);

extern "C" PRINCIPIA_DLL
void CDECL principia__UpdatePrediction(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
XYZ CDECL principia__VesselBinormal(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
QP CDECL principia__VesselFromParent(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
AdaptiveStepParameters CDECL principia__VesselGetPredictionAdaptiveStepParameters(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
XYZ CDECL principia__VesselNormal(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
void CDECL principia__VesselSetPredictionAdaptiveStepParameters(
    Plugin const* const plugin,
    char const* const vessel_guid,
    AdaptiveStepParameters const adaptive_step_parameters);

extern "C" PRINCIPIA_DLL
XYZ CDECL principia__VesselTangent(
    Plugin const* const plugin,
    char const* const vessel_guid);

extern "C" PRINCIPIA_DLL
XYZ CDECL principia__VesselVelocity(
    Plugin const* const plugin,
    char const* const vessel_guid);

